import Link from "next/link";
import { AppShell } from "@/components/layout/app-shell";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { requirePermission, PERMISSIONS } from "@/server/auth/permissions";
import { prisma } from "@/server/db/prisma";

export default async function SalesPage({ searchParams }: { searchParams: Promise<{ search?: string; from?: string; to?: string }> }) {
  const user = await requirePermission(PERMISSIONS.salesView);
  const params = await searchParams;
  const dateFilter = params.from || params.to ? { invoiceDate: { ...(params.from ? { gte: new Date(`${params.from}T00:00:00.000Z`) } : {}), ...(params.to ? { lte: new Date(`${params.to}T23:59:59.999Z`) } : {}) } } : {};
  const searchFilter = params.search ? { OR: [{ invoiceNumber: { contains: params.search, mode: "insensitive" as const } }, { customer: { name: { contains: params.search, mode: "insensitive" as const } } }, { items: { some: { medicine: { name: { contains: params.search, mode: "insensitive" as const } } } } }] } : {};
  const sales = await prisma.sale.findMany({ where: { ...dateFilter, ...searchFilter }, include: { customer: true, items: { include: { medicine: true } } }, orderBy: { invoiceDate: "desc" }, take: 200 });
  return <AppShell user={user}><div className="mx-auto max-w-6xl space-y-6"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Customers</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Customer bills</h1><p className="mt-2 text-muted-foreground">Create bills, collect payments and track profit.</p></div><Link href="/sales/new" className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-4 text-sm font-semibold text-primary-foreground">+ Add customer bill</Link></div><Card><CardHeader><CardTitle>Recent bills</CardTitle><form className="mt-4 grid gap-3 md:grid-cols-4"><Input name="search" defaultValue={params.search} placeholder="Invoice, customer, or medicine" /><Input name="from" type="date" defaultValue={params.from} /><Input name="to" type="date" defaultValue={params.to} /><Button>Filter</Button></form></CardHeader><CardContent>{sales.length === 0 ? <p className="py-10 text-center text-sm text-muted-foreground">No matching bills.</p> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-muted-foreground"><th className="pb-3">Invoice</th><th className="pb-3">Customer</th><th className="pb-3">Medicines given</th><th className="pb-3">Date</th><th className="pb-3">Total</th><th className="pb-3">Paid</th><th className="pb-3">Profit</th><th className="pb-3">Action</th></tr></thead><tbody>{sales.map((sale) => <tr key={sale.id} className="border-b last:border-0"><td className="py-3 font-medium">{sale.invoiceNumber}</td><td className="py-3">{sale.customer?.name ?? "Walk-in"}</td><td className="max-w-xs py-3">{sale.items.map((item) => `${item.medicine.name} (${item.quantity})`).join(", ")}</td><td className="py-3">{sale.invoiceDate.toLocaleDateString()}</td><td className="py-3">{sale.grandTotal.toFixed(2)}</td><td className="py-3">{sale.paidAmount.toFixed(2)}</td><td className="py-3">{(sale.grandTotal - sale.costAmount).toFixed(2)}</td><td className="py-3"><Link href={`/sales/${sale.id}`} className="font-semibold text-primary hover:underline">View bill</Link></td></tr>)}</tbody></table></div>}</CardContent></Card></div></AppShell>;
}
