import { AppShell } from "@/components/layout/app-shell";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { CustomerForm } from "@/components/customers/customer-form";
import { requirePermission, PERMISSIONS } from "@/server/auth/permissions";
import { listCustomers } from "@/server/services/customer.service";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { LiveFilterForm } from "@/components/filters/live-filter-form";
import { CustomerActions } from "@/components/customers/customer-actions";
export default async function CustomersPage({ searchParams }: { searchParams: Promise<{ search?: string }> }){const user=await requirePermission(PERMISSIONS.customersView);const params=await searchParams;const customers=await listCustomers(params.search);return <AppShell user={user}><div className="mx-auto max-w-6xl space-y-6"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Customers</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Customer directory</h1><p className="mt-2 text-muted-foreground">Add customers, edit their contact details and track outstanding credit.</p></div><CustomerForm/><Card><CardHeader><CardTitle>Customers</CardTitle><LiveFilterForm fields={["search"]}><div className="flex gap-2"><Input name="search" defaultValue={params.search} placeholder="Search customer, mobile, or email" /><Button type="submit">Search</Button></div></LiveFilterForm></CardHeader><CardContent>{customers.length===0?<p className="py-10 text-center text-sm text-muted-foreground">No customers found.</p>:<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-muted-foreground"><th className="pb-3">Name</th><th className="pb-3">Mobile</th><th className="pb-3">Email</th><th className="pb-3">Outstanding</th><th className="pb-3">Status</th><th className="pb-3">Action</th></tr></thead><tbody>{customers.map(customer=><tr key={customer.id} className="border-b last:border-0"><td className="py-3 font-medium">{customer.name}</td><td className="py-3">{customer.mobile??"-"}</td><td className="py-3">{customer.email??"-"}</td><td className="py-3">{customer.outstandingBalance.toFixed(2)}</td><td className="py-3">{customer.status}</td><td className="py-3"><div className="flex items-center gap-2"><Link className="font-semibold text-primary hover:underline" href={`/customers/${customer.id}/edit`}>Edit</Link><CustomerActions id={customer.id} name={customer.name} /></div></td></tr>)}</tbody></table></div>}</CardContent></Card></div></AppShell>}
