import { AppShell } from "@/components/layout/app-shell";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { StockAdjustmentForm } from "@/components/inventory/stock-adjustment-form";
import { requirePermission, PERMISSIONS } from "@/server/auth/permissions";
import { getInventorySummary } from "@/server/services/inventory.service";

export default async function InventoryPage() {
  const user = await requirePermission(PERMISSIONS.inventoryView);
  const summary = await getInventorySummary();
  return <AppShell user={user}><div className="mx-auto max-w-[1440px] space-y-6"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Inventory</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Stock control</h1><p className="mt-2 text-muted-foreground">Real batch stock and expiry visibility from MongoDB.</p></div><StockAdjustmentForm batches={summary.batches} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Stock units", summary.totalStock], ["Stock value", summary.stockValue.toFixed(2)], ["Low stock", summary.lowStock.length], ["Expired / near expiry", `${summary.expired.length} / ${summary.nearExpiry.length}`]].map(([label, value]) => <Card key={String(label)}><CardContent className="pt-6"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-semibold">{String(value)}</p></CardContent></Card>)}</div>{summary.lowStock.length > 0 && <Card className="border-amber-300 bg-amber-50/50"><CardHeader><CardTitle className="text-amber-900">Low stock medicines</CardTitle></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{summary.lowStock.map((batch) => <div key={batch.id} className="rounded-lg border border-amber-200 bg-white p-3"><p className="font-semibold text-amber-950">{batch.medicine.name}</p><p className="text-sm text-amber-800">Batch: {batch.batchNumber}</p><p className="mt-1 text-sm"><strong>{batch.quantity + batch.freeQuantity}</strong> remaining / minimum {batch.medicine.minimumStock}</p></div>)}</div></CardContent></Card>}<Card><CardHeader><CardTitle>Batch-wise stock</CardTitle></CardHeader><CardContent>{summary.batches.length === 0 ? <p className="py-10 text-center text-sm text-muted-foreground">No batches recorded yet.</p> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-muted-foreground"><th className="pb-3">Medicine</th><th className="pb-3">Batch</th><th className="pb-3">Expiry</th><th className="pb-3">Quantity</th><th className="pb-3">Status</th></tr></thead><tbody>{summary.batches.map((batch) => <tr key={batch.id} className="border-b last:border-0"><td className="py-3 font-medium">{batch.medicine.name}</td><td className="py-3">{batch.batchNumber}</td><td className="py-3">{batch.expiryDate.toLocaleDateString()}</td><td className="py-3">{batch.quantity + batch.freeQuantity}</td><td className="py-3">{summary.expired.some((item) => item.id === batch.id) ? "Expired" : summary.nearExpiry.some((item) => item.id === batch.id) ? "Near expiry" : "In stock"}</td></tr>)}</tbody></table></div>}</CardContent></Card></div></AppShell>;
}
