"use client";

import { useState, type ReactNode } from "react";
import { useRouter } from "next/navigation";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Option = { id: string; name: string };
type MedicineValues = { id?: string; name?: string; genericName?: string | null; composition?: string | null; categoryId?: string | null; manufacturerId?: string | null; dosageForm?: string | null; strength?: string | null; packSize?: string | null; unit?: string; hsnCode?: string | null; gstPercentage?: number; prescriptionRequired?: boolean; barcode?: string | null; sku?: string; mrp?: number; purchasePrice?: number; sellingPrice?: number; minimumStock?: number; active?: boolean };

export function MedicineForm({ categories, manufacturers, initial = {} }: { categories: Option[]; manufacturers: Option[]; initial?: MedicineValues }) {
  const router = useRouter(); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); const form = new FormData(event.currentTarget); const body = Object.fromEntries(form); body.prescriptionRequired = form.has("prescriptionRequired") as unknown as FormDataEntryValue; body.active = form.has("active") as unknown as FormDataEntryValue; const response = await fetch(initial.id ? `/api/medicines/${initial.id}` : "/api/medicines", { method: initial.id ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (!response.ok) { const result = await response.json(); setError(result.error ?? "Unable to save medicine."); setSaving(false); return; } router.push("/medicines"); router.refresh(); }
  return <form onSubmit={submit} className="space-y-6"><div className="grid gap-4 md:grid-cols-3"><Field id="name" label="Medicine name" defaultValue={initial.name} required /><Field id="genericName" label="Generic name" defaultValue={initial.genericName ?? ""} /><Field id="composition" label="Salt / composition" defaultValue={initial.composition ?? ""} /><Field id="categoryId" label="Category"><select name="categoryId" defaultValue={initial.categoryId ?? ""} className="h-10 w-full rounded-md border bg-surface px-3 text-sm"><option value="">Select category</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field id="manufacturerId" label="Manufacturer"><select name="manufacturerId" defaultValue={initial.manufacturerId ?? ""} className="h-10 w-full rounded-md border bg-surface px-3 text-sm"><option value="">Select manufacturer</option>{manufacturers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field id="dosageForm" label="Dosage form" defaultValue={initial.dosageForm ?? ""} /><Field id="strength" label="Strength" defaultValue={initial.strength ?? ""} /><Field id="packSize" label="Pack size" defaultValue={initial.packSize ?? ""} /><Field id="unit" label="Unit" defaultValue={initial.unit ?? "piece"} required /><Field id="hsnCode" label="HSN code" defaultValue={initial.hsnCode ?? ""} /><Field id="gstPercentage" label="GST %" type="number" defaultValue={initial.gstPercentage ?? 0} required /><Field id="sku" label="SKU" defaultValue={initial.sku} required /><Field id="barcode" label="Barcode" defaultValue={initial.barcode ?? ""} /><Field id="mrp" label="MRP" type="number" step="0.01" defaultValue={initial.mrp ?? 0} required /><Field id="purchasePrice" label="Purchase price" type="number" step="0.01" defaultValue={initial.purchasePrice ?? 0} required /><Field id="sellingPrice" label="Selling price" type="number" step="0.01" defaultValue={initial.sellingPrice ?? 0} required /><Field id="minimumStock" label="Minimum stock" type="number" defaultValue={initial.minimumStock ?? 0} required /></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="prescriptionRequired" defaultChecked={initial.prescriptionRequired} /> Prescription required</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="active" defaultChecked={initial.active ?? true} /> Active</label>{error && <p role="alert" className="text-sm text-red-600">{error}</p>}<Button disabled={saving}>{saving ? "Saving..." : initial.id ? "Update medicine" : "Add medicine"}</Button></form>;
}

function Field({ id, label, type = "text", step, defaultValue, required, children }: { id: string; label: string; type?: string; step?: string; defaultValue?: string | number; required?: boolean; children?: ReactNode }) { return <div className="space-y-2"><label htmlFor={id} className="text-sm font-medium">{label}</label>{children ?? <Input id={id} name={id} type={type} step={step} defaultValue={defaultValue} required={required} />}</div>; }
