import { NextResponse } from "next/server";
import { ZodError } from "zod";

import { requirePermission, PERMISSIONS } from "@/server/auth/permissions";
import { deleteMedicine, updateMedicine } from "@/server/services/medicine.service";
import { prisma } from "@/server/db/prisma";

export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) { const user = await requirePermission(PERMISSIONS.medicineView); const { id } = await params; const medicine = await prisma.medicine.findUnique({ where: { id }, include: { category: true, manufacturer: true, batches: { where: { pharmacyId: user.pharmacyId } } } }); return medicine ? NextResponse.json(medicine) : NextResponse.json({ error: "Medicine not found." }, { status: 404 }); }
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { try { const user = await requirePermission(PERMISSIONS.medicineUpdate); const { id } = await params; return NextResponse.json(await updateMedicine(id, await request.json(), user.id)); } catch (error) { console.error("Medicine update failed", error); const message = error instanceof Error ? error.message : "Unable to update medicine."; if (error instanceof ZodError) return NextResponse.json({ error: "Unable to update medicine. Check the submitted fields.", fields: error.flatten().fieldErrors }, { status: 422 }); const status = message.includes("already in use") ? 409 : message === "Medicine not found." ? 404 : message.includes("Invalid medicine ID") ? 400 : 422; return NextResponse.json({ error: status === 422 ? message : message }, { status }); } }
export async function DELETE(_request: Request, { params }: { params: Promise<{ id: string }> }) { try { await requirePermission(PERMISSIONS.medicineDelete); const { id } = await params; return NextResponse.json(await deleteMedicine(id)); } catch (error) { console.error("Medicine delete failed", error); const message = error instanceof Error ? error.message : "Unable to delete medicine."; return NextResponse.json({ error: message }, { status: message === "Medicine not found." ? 404 : 400 }); } }
