import Link from "next/link";
import { notFound } from "next/navigation";
import { AppShell } from "@/components/layout/app-shell";
import { InvoiceActions } from "@/components/purchases/invoice-actions";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { requirePermission, PERMISSIONS } from "@/server/auth/permissions";
import { prisma } from "@/server/db/prisma";

export default async function PurchaseDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const user = await requirePermission(PERMISSIONS.purchaseView);
  const { id } = await params;
  const purchase = await prisma.purchase.findUnique({ where: { id }, include: { supplier: true, items: { include: { medicine: true, batch: true } }, payments: true } });
  if (!purchase) notFound();

  return <AppShell user={user}><div className="invoice-sheet mx-auto max-w-6xl space-y-6"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Purchase invoice</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Invoice {purchase.invoiceNumber}</h1><p className="mt-2 text-muted-foreground">{purchase.supplier?.businessName ?? "Supplier unavailable"} · {purchase.invoiceDate.toLocaleDateString()}</p></div><div className="flex items-center gap-2"><InvoiceActions /><Link href="/purchases" className="rounded-md border px-4 py-2 text-sm font-semibold hover:bg-muted print:hidden">Back</Link></div></div><Card><CardHeader><CardTitle>Wholesaler purchase bill</CardTitle><p className="text-sm text-muted-foreground">Wholesaler: {purchase.supplier?.businessName ?? "Unavailable"} · Invoice: {purchase.invoiceNumber}</p></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-muted-foreground"><th className="pb-3">Medicine</th><th className="pb-3">Batch</th><th className="pb-3">Expiry</th><th className="pb-3">Qty</th><th className="pb-3">Purchase rate</th><th className="pb-3">MRP</th><th className="pb-3">Selling price</th><th className="pb-3">Total</th></tr></thead><tbody>{purchase.items.map((item) => <tr key={item.id} className="border-b last:border-0"><td className="py-3 font-medium">{item.medicine.name}<span className="block text-xs text-muted-foreground">{item.medicine.sku}</span></td><td className="py-3">{item.batch.batchNumber}</td><td className="py-3">{item.expiryDate.toLocaleDateString()}</td><td className="py-3">{item.quantity} + {item.freeQuantity}</td><td className="py-3">{item.purchaseRate.toFixed(2)}</td><td className="py-3">{item.mrp.toFixed(2)}</td><td className="py-3">{item.sellingPrice.toFixed(2)}</td><td className="py-3">{item.lineTotal.toFixed(2)}</td></tr>)}</tbody></table></div><div className="ml-auto mt-6 max-w-sm space-y-2 border-t pt-4 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>{purchase.subtotal.toFixed(2)}</span></div><div className="flex justify-between"><span>Discount</span><span>{purchase.discount.toFixed(2)}</span></div><div className="flex justify-between text-base font-semibold"><span>Grand total</span><span>{purchase.grandTotal.toFixed(2)}</span></div><div className="flex justify-between text-emerald-700"><span>Paid to wholesaler</span><span>{purchase.paidAmount.toFixed(2)}</span></div><div className="flex justify-between font-semibold text-amber-700"><span>Supplier balance</span><span>{purchase.balanceAmount.toFixed(2)}</span></div></div></CardContent></Card></div></AppShell>;
}
