import Link from "next/link";
import { AppShell } from "@/components/layout/app-shell";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { requirePermission, PERMISSIONS } from "@/server/auth/permissions";
import { listPurchases } from "@/server/services/purchase.service";
import { prisma } from "@/server/db/prisma";

export default async function PurchasesPage({ searchParams }: { searchParams: Promise<{ search?: string; supplierId?: string; from?: string; to?: string; page?: string }> }) {
  const user = await requirePermission(PERMISSIONS.purchaseView);
  const params = await searchParams;
  const page = Math.max(1, Number(params.page ?? 1));
  const [result, suppliers] = await Promise.all([
    listPurchases({ search: params.search, supplierId: params.supplierId, from: params.from ? new Date(`${params.from}T00:00:00.000Z`) : undefined, to: params.to ? new Date(`${params.to}T23:59:59.999Z`) : undefined, page }),
    prisma.supplier.findMany({ where: { status: "ACTIVE" }, select: { id: true, businessName: true }, orderBy: { businessName: "asc" } }),
  ]);
  const query = (nextPage: number) => new URLSearchParams({ ...(params.search ? { search: params.search } : {}), ...(params.supplierId ? { supplierId: params.supplierId } : {}), ...(params.from ? { from: params.from } : {}), ...(params.to ? { to: params.to } : {}), page: String(nextPage) }).toString();
  return <AppShell user={user}><div className="mx-auto max-w-6xl space-y-6"><div className="flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Purchasing</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Purchase history</h1></div><Link href="/purchases/new" className="rounded-md bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">New purchase</Link></div><Card><CardHeader><CardTitle>Completed purchases</CardTitle><form className="mt-4 grid gap-3 md:grid-cols-4"><Input name="search" defaultValue={params.search} placeholder="Invoice number" /><select name="supplierId" defaultValue={params.supplierId ?? ""} className="h-10 rounded-md border bg-background px-3 text-sm"><option value="">All suppliers</option>{suppliers.map((supplier) => <option key={supplier.id} value={supplier.id}>{supplier.businessName}</option>)}</select><Input name="from" type="date" defaultValue={params.from} aria-label="From date" /><div className="flex gap-2"><Input name="to" type="date" defaultValue={params.to} aria-label="To date" /><button className="rounded-md bg-primary px-3 text-sm font-semibold text-primary-foreground">Filter</button></div></form></CardHeader><CardContent>{result.items.length === 0 ? <p className="py-10 text-center text-sm text-muted-foreground">No purchases found for these filters.</p> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-muted-foreground"><th className="pb-3">Invoice</th><th className="pb-3">Supplier</th><th className="pb-3">Date</th><th className="pb-3">Total</th><th className="pb-3">Paid</th><th className="pb-3">Balance</th></tr></thead><tbody>{result.items.map((purchase) => <tr key={purchase.id} className="border-b last:border-0"><td className="py-3 font-medium"><Link href={`/purchases/${purchase.id}`} className="text-primary hover:underline">{purchase.invoiceNumber}</Link></td><td className="py-3">{purchase.supplier?.businessName ?? "Supplier unavailable"}</td><td className="py-3">{purchase.invoiceDate.toLocaleDateString()}</td><td className="py-3">{purchase.grandTotal.toFixed(2)}</td><td className="py-3">{purchase.paidAmount.toFixed(2)}</td><td className="py-3">{purchase.balanceAmount.toFixed(2)}</td></tr>)}</tbody></table></div>}<div className="mt-5 flex items-center justify-between text-sm text-muted-foreground"><span>Page {result.page} of {result.pageCount} · {result.total} purchase(s)</span><div className="flex gap-2">{result.page > 1 && <Link className="rounded-md border px-3 py-2 hover:bg-muted" href={`/purchases?${query(result.page - 1)}`}>Previous</Link>}{result.page < result.pageCount && <Link className="rounded-md border px-3 py-2 hover:bg-muted" href={`/purchases?${query(result.page + 1)}`}>Next</Link>}</div></div></CardContent></Card></div></AppShell>;
}
