import Link from "next/link";
import { Plus, Search } from "lucide-react";

import { AppShell } from "@/components/layout/app-shell";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { requirePermission, PERMISSIONS } from "@/server/auth/permissions";
import { listCategories, listManufacturers, listMedicines } from "@/server/services/medicine.service";
import { MedicineActions } from "@/components/medicines/medicine-actions";

export default async function MedicinesPage({ searchParams }: { searchParams: Promise<{ search?: string }> }) {
  const user = await requirePermission(PERMISSIONS.medicineView);
  const { search = "" } = await searchParams;
  const [medicines, categories, manufacturers] = await Promise.all([listMedicines(search), listCategories(), listManufacturers()]);
  return <AppShell user={user}><div className="mx-auto max-w-[1440px] space-y-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Medicine master</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Medicines</h1><p className="mt-2 text-muted-foreground">Manage medicine details, pricing, and status.</p></div><Link href="/medicines/new" className="inline-flex h-10 items-center justify-center gap-2 rounded-md bg-primary px-4 text-sm font-semibold text-primary-foreground hover:opacity-90"><Plus className="size-4" /> Add medicine</Link></div><Card><CardHeader><CardTitle>Medicine catalogue</CardTitle><form className="relative mt-4 max-w-sm"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input name="search" defaultValue={search} placeholder="Search name, generic, or SKU" className="pl-9" /></form></CardHeader><CardContent>{medicines.length === 0 ? <p className="py-12 text-center text-sm text-muted-foreground">No medicines found. Add the first medicine to begin.</p> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-muted-foreground"><th className="pb-3">Name</th><th className="pb-3">SKU</th><th className="pb-3">Category</th><th className="pb-3">Stock</th><th className="pb-3">Selling price</th><th className="pb-3">Status</th><th className="pb-3">Actions</th></tr></thead><tbody>{medicines.map((medicine) => <tr key={medicine.id} className="border-b last:border-0"><td className="py-3 font-medium">{medicine.name}<span className="block text-xs text-muted-foreground">{medicine.genericName}</span></td><td className="py-3">{medicine.sku}</td><td className="py-3">{medicine.category?.name ?? "-"}</td><td className="py-3">{medicine.batches.reduce((sum, batch) => sum + batch.quantity + batch.freeQuantity, 0)}</td><td className="py-3">{medicine.sellingPrice.toFixed(2)}</td><td className="py-3">{medicine.active ? "Active" : "Inactive"}</td><td className="py-3"><MedicineActions id={medicine.id} name={medicine.name} active={medicine.active} /></td></tr>)}</tbody></table></div>}</CardContent></Card><p className="text-xs text-muted-foreground">{categories.length} active categories, {manufacturers.length} active manufacturers.</p></div></AppShell>;
}
